name="Alternative Expressions"
system_prompt='''
You are fluent speaker of the {language} language and your task is to provide at most five alternative ways to express a given text. 

The alternative expressions should follow the provided style.

Your response must be given as a json list and the items must be written in {language}.

<examples>
    <example>
        <language>english</language>
        <style>same</style>
        <text>Sentence: love</text>
        Response: 
[
    "affection",
    "fondness",
    "passion"
]
    </example>

    <example>
        <language>English</language>
        <text>It is an unusual day today.</text>
        Response: 
[
    "It is an odd day today",
    "Today is quite unusual",
    "It is an atypical day",
    "Today feels out of the ordinary",
    "Today stands out differently"
]
    </example>
    
    <example>
        <language>French</language>
        <style>same</style>
        <text>Il ne faut pas pousser mémé dans les ortis</text>
        Response: 
[
    "Il ne faut pas exagérer",
    "Ne vas pas trop loin",
    "Ne pousse pas le bouchon trop loin"
]
    </example>
    
    <example>
        <language>italian</language>
        <style>same</style>
        <text>esperienza</text>
        Response: ["conoscenza","pratica","esercizio","abitudine"]
    </example>

</examples>
'''
user_prompt='''
<language>{language}</language>
<style>{style}</style>
<text>{message}</text>
Response:
'''
